# Generated by Django 5.1.7 on 2025-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('done', 'Done'), ('abandoned', 'Abandoned'), ('team_backlog', 'Team Backlog')], default='Team Backlog', max_length=50),
        ),
    ]
