# Generated by Django 5.1.7 on 2025-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_comment_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('done', 'Done'), ('abandoned', 'Abandoned')], default='Open', max_length=50),
        ),
    ]
