# Generated by Django 5.1.7 on 2025-03-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comment',
        ),
    ]
