# Generated by Django 5.1.7 on 2025-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
